In [1]:
# Crear datasets relacionados:
import pandas as pd
import numpy as np

# Dataset de ventas
ventas = pd.DataFrame({
    'id_venta': range(1, 11),
    'id_cliente': np.random.choice([1, 2, 3, 4, 5], 10),
    'id_producto': np.random.choice([101, 102, 103, 104], 10),
    'cantidad': np.random.randint(1, 5, 10),
    'fecha': pd.date_range('2024-01-01', periods=10, freq='D')
})

# Dataset de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4, 5],
    'nombre': ['Ana', 'Carlos', 'María', 'Juan', 'Luis'],
    'ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Valencia', 'Sevilla']
})

# Dataset de productos
productos = pd.DataFrame({
    'id_producto': [101, 102, 103, 104],
    'nombre': ['Laptop', 'Mouse', 'Teclado', 'Monitor'],
    'precio': [1200, 25, 80, 300],
    'categoria': ['Electrónica', 'Accesorios', 'Accesorios', 'Electrónica']
})

print("Datasets creados:")
print(f"Ventas: {ventas.shape}")
print(f"Clientes: {clientes.shape}")
print(f"Productos: {productos.shape}")

Datasets creados:
Ventas: (10, 5)
Clientes: (5, 3)
Productos: (4, 4)

In [2]:
ventas

   id_venta  id_cliente  id_producto  cantidad      fecha
0         1           1          103         2 2024-01-01
1         2           2          101         2 2024-01-02
2         3           5          101         1 2024-01-03
3         4           2          101         4 2024-01-04
4         5           2          103         3 2024-01-05
5         6           3          103         1 2024-01-06
6         7           5          101         3 2024-01-07
7         8           4          103         3 2024-01-08
8         9           4          104         3 2024-01-09
9        10           5          104         3 2024-01-10

In [4]:
clientes

   id_cliente  nombre     ciudad
0           1     Ana     Madrid
1           2  Carlos  Barcelona
2           3   María     Madrid
3           4    Juan   Valencia
4           5    Luis    Sevilla

In [5]:
productos

   id_producto   nombre  precio    categoria
0          101   Laptop    1200  Electrónica
1          102    Mouse      25   Accesorios
2          103  Teclado      80   Accesorios
3          104  Monitor     300  Electrónica

In [6]:
# Filtrado avanzado con query():
# Ventas del mes actual con query
ventas_recientes = ventas.query('fecha >= "2024-01-05"')
print(f"\nVentas recientes: {len(ventas_recientes)}")

Ventas recientes: 6

In [7]:
# Productos caros usando variable externa
precio_limite = 100
productos_caros = productos.query('precio >= @precio_limite')
print(f"Productos caros (>= {precio_limite}): {productos_caros['nombre'].tolist()}")

Productos caros (>= 100): ['Laptop', 'Monitor']

In [8]:
# Agrupación y agregación:
# Ventas por producto
ventas_por_producto = ventas.groupby('id_producto')['cantidad'].sum()
print(f"\nVentas por producto:\n{ventas_por_producto}")

Ventas por producto:
id_producto
101    10
103     9
104     6
Name: cantidad, dtype: int32

In [9]:
# Estadísticas por cliente
stats_por_cliente = ventas.groupby('id_cliente').agg({
    'cantidad': ['sum', 'mean'],
    'id_venta': 'count'
})
print(f"\nEstadísticas por cliente:\n{stats_por_cliente}")

Estadísticas por cliente:
           cantidad           id_venta
                sum      mean    count
id_cliente
1                 2  2.000000        1
2                 9  3.000000        3
3                 1  1.000000        1
4                 6  3.000000        2
5                 7  2.333333        3

In [10]:
# Merge para análisis completo:
# Unir ventas con productos
ventas_productos = pd.merge(ventas, productos, on='id_producto')

In [11]:
ventas_productos

,id_venta,id_cliente,id_producto,cantidad,fecha,nombre,precio,categoria
0,1,1,103,2,2024-01-01,Teclado,80,Accesorios
1,5,2,103,3,2024-01-05,Teclado,80,Accesorios
2,6,3,103,1,2024-01-06,Teclado,80,Accesorios
3,8,4,103,3,2024-01-08,Teclado,80,Accesorios
4,2,2,101,2,2024-01-02,Laptop,1200,Electrónica
5,3,5,101,1,2024-01-03,Laptop,1200,Electrónica
6,4,2,101,4,2024-01-04,Laptop,1200,Electrónica
7,7,5,101,3,2024-01-07,Laptop,1200,Electrónica
8,9,4,104,3,2024-01-09,Monitor,300,Electrónica
9,10,5,104,3,2024-01-10,Monitor,300,Electrónica

In [12]:
# Calcular totales
ventas_productos['total'] = ventas_productos['cantidad'] * ventas_productos['precio']

In [13]:
ventas_productos

,id_venta,id_cliente,id_producto,cantidad,fecha,nombre,precio,categoria,total
0,1,1,103,2,2024-01-01,Teclado,80,Accesorios,160
1,5,2,103,3,2024-01-05,Teclado,80,Accesorios,240
2,6,3,103,1,2024-01-06,Teclado,80,Accesorios,80
3,8,4,103,3,2024-01-08,Teclado,80,Accesorios,240
4,2,2,101,2,2024-01-02,Laptop,1200,Electrónica,2400
5,3,5,101,1,2024-01-03,Laptop,1200,Electrónica,1200
6,4,2,101,4,2024-01-04,Laptop,1200,Electrónica,4800
7,7,5,101,3,2024-01-07,Laptop,1200,Electrónica,3600
8,9,4,104,3,2024-01-09,Monitor,300,Electrónica,900
9,10,5,104,3,2024-01-10,Monitor,300,Electrónica,900

In [14]:
# Unir con clientes
analisis_completo = pd.merge(ventas_productos, clientes, on='id_cliente')

print(f"\nAnálisis completo (primeras 5 filas):\n{analisis_completo.head()}")

Análisis completo (primeras 5 filas):
   id_venta  id_cliente  id_producto  cantidad      fecha nombre_x  precio  \
0         1           1          103         2 2024-01-01  Teclado      80
1         5           2          103         3 2024-01-05  Teclado      80
2         2           2          101         2 2024-01-02   Laptop    1200
3         4           2          101         4 2024-01-04   Laptop    1200
4         6           3          103         1 2024-01-06  Teclado      80

     categoria  total nombre_y     ciudad
0   Accesorios    160      Ana     Madrid
1   Accesorios    240   Carlos  Barcelona
2  Electrónica   2400   Carlos  Barcelona
3  Electrónica   4800   Carlos  Barcelona
4   Accesorios     80    María     Madrid

In [15]:
# Análisis por ciudad
ventas_por_ciudad = analisis_completo.groupby('ciudad')['total'].sum()
print(f"\nVentas totales por ciudad:\n{ventas_por_ciudad}")

Ventas totales por ciudad:
ciudad
Barcelona    7440
Madrid        240
Sevilla      5700
Valencia     1140
Name: total, dtype: int64

In [21]:
analisis_completo

,id_venta,id_cliente,id_producto,cantidad,fecha,nombre_x,precio,categoria,total,nombre_y,ciudad
0,1,1,103,2,2024-01-01,Teclado,80,Accesorios,160,Ana,Madrid
1,5,2,103,3,2024-01-05,Teclado,80,Accesorios,240,Carlos,Barcelona
2,2,2,101,2,2024-01-02,Laptop,1200,Electrónica,2400,Carlos,Barcelona
3,4,2,101,4,2024-01-04,Laptop,1200,Electrónica,4800,Carlos,Barcelona
4,6,3,103,1,2024-01-06,Teclado,80,Accesorios,80,María,Madrid
5,8,4,103,3,2024-01-08,Teclado,80,Accesorios,240,Juan,Valencia
6,9,4,104,3,2024-01-09,Monitor,300,Electrónica,900,Juan,Valencia
7,3,5,101,1,2024-01-03,Laptop,1200,Electrónica,1200,Luis,Sevilla
8,7,5,101,3,2024-01-07,Laptop,1200,Electrónica,3600,Luis,Sevilla
9,10,5,104,3,2024-01-10,Monitor,300,Electrónica,900,Luis,Sevilla

In [22]:
clientes_top = (
    analisis_completo
    .groupby(['id_cliente','nombre_y'], as_index=False)['total']
    .sum()
)
clientes_top = clientes_top[clientes_top['total'] > 1000]

print("\nClientes con compras > 1000:\n", clientes_top)

Clientes con compras > 1000:
    id_cliente nombre_y  total
1           2   Carlos   7440
3           4     Juan   1140
4           5     Luis   5700

In [25]:
analisis_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     10 non-null     int64
 1   id_cliente   10 non-null     int32
 2   id_producto  10 non-null     int32
 3   cantidad     10 non-null     int32
 4   fecha        10 non-null     datetime64[ns]
 5   nombre_x     10 non-null     object
 6   precio       10 non-null     int64
 7   categoria    10 non-null     object
 8   total        10 non-null     int64
 9   nombre_y     10 non-null     object
 10  ciudad       10 non-null     object
dtypes: datetime64[ns](1), int32(3), int64(3), object(4)
memory usage: 892.0+ bytes